// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/mime;

# This is the client for the Zuora Revenue REST API, used to upload data, track uploads and staging errors, download BI view data and reports, transfer accounting batches, and submit and monitor revenue programs and data collection jobs.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://yourHost/api/integration") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Create authentication
    #
    # + headers - Headers to be sent with the request 
    # + return - Authentication token is returned 
    remote isolated function createAuthentication(CreateAuthenticationHeaders headers = {}) returns AuthenticationResponse|error {
        string resourcePath = string `/v1/authenticate`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get file upload status
    #
    # + fileRequestId - The request ID of the file upload to be queried
    # + headers - Headers to be sent with the request 
    # + return - The status information is returned for the requested file upload 
    remote isolated function getFileUploadStatus(int fileRequestId, GetFileUploadStatusHeaders headers) returns FileUploadStatusResponse|error? {
        string resourcePath = string `/v1/fileupload/status/${getEncodedUri(fileRequestId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Upload file
    #
    # + headers - Headers to be sent with the request 
    # + payload - Multipart form with the CSV file to upload and its upload options 
    # + return - The file is uploaded to Zuora Revenue 
    remote isolated function uploadFile(UploadFileHeaders headers, UploadFileBody payload) returns UploadFileResponse|error {
        string resourcePath = string `/v1/upload/file`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get upload status
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The status information is returned for the requested upload 
    remote isolated function getUploadStatus(GetUploadStatusHeaders headers, *GetUploadStatusQueries queries) returns UploadStatusResponse|error {
        string resourcePath = string `/v1/csv/upload/status`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create upload
    #
    # + headers - Headers to be sent with the request 
    # + payload - CSV lines of transaction, event or bundle configuration data to upload 
    # + return - Data is uploaded to the staging tables in Zuora Revenue 
    remote isolated function createUpload(CreateUploadHeaders headers, string[] payload) returns CreateUploadResponse|error {
        string resourcePath = string `/v1/csv/upload`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        request.setPayload(payload, "text/plain");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Update transfer batch status
    #
    # + batchId - The batch ID of the transfer accounting batch
    # + headers - Headers to be sent with the request 
    # + return - The status of the transfer batch is changed to `Transferred` 
    remote isolated function updateTransferBatchStatus(int batchId, UpdateTransferBatchStatusHeaders headers) returns TransferBatchStatusResponse|error {
        string resourcePath = string `/v1/journal/batch/status/${getEncodedUri(batchId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Get transfer batch
    #
    # + batchid - The batch ID of the transfer accounting batch
    # + pagenum - The number of page to be downloaded
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The GL transfer batch data for the requested batch ID and page is returned 
    remote isolated function getTransferBatch(int batchid, int pagenum, GetTransferBatchHeaders headers, *GetTransferBatchQueries queries) returns TransferBatchStatusResponse|error {
        string resourcePath = string `/v1/journal/batch/${getEncodedUri(batchid)}/${getEncodedUri(pagenum)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get BI Views
    #
    # + viewName - Name of the BI view
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - BI view data is returned in CSV format 
    remote isolated function getBiViews(string viewName, GetBiViewsHeaders headers, *GetBiViewsQueries queries) returns error? {
        string resourcePath = string `/v1/biviews/${getEncodedUri(viewName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get BI View data for selected fields
    #
    # + viewName - Name of the BI view
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - List of field names to be selected from the BI view 
    # + return - BI view data is returned in CSV format 
    remote isolated function getBiViewsForFields(string viewName, GetBiViewsForFieldsHeaders headers, string[] payload, *GetBiViewsForFieldsQueries queries) returns error? {
        string resourcePath = string `/v1/biviews/${getEncodedUri(viewName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get transfer batch list
    #
    # + headers - Headers to be sent with the request 
    # + return - The list of available transfer accounting batches is returned 
    remote isolated function listTransferBatches(ListTransferBatchesHeaders headers) returns TransferBatchListResponse|error? {
        string resourcePath = string `/v1/journal/list`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get transfer batch file
    #
    # + batchId - The batch ID of the transfer accounting batch
    # + headers - Headers to be sent with the request 
    # + return - The GL transfer batch file for the requested batch ID is returned 
    remote isolated function getTransferBatchFile(int batchId, GetTransferBatchFileHeaders headers) returns TransferBatchFileResponse|error? {
        string resourcePath = string `/v1/download/transferbatchfile/${getEncodedUri(batchId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get report list
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The list of reports created on the specified date is returned 
    remote isolated function listReports(ListReportsHeaders headers, *ListReportsQueries queries) returns ReportListResponse|error {
        string resourcePath = string `/v1/reports/list`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Download a report
    #
    # + filename - The name of the report file to be downloaded
    # + headers - Headers to be sent with the request 
    # + return - The report file is returned 
    remote isolated function downloadReport(string filename, DownloadReportHeaders headers) returns error? {
        string resourcePath = string `/v1/reports/download/${getEncodedUri(filename)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get report signed URL
    #
    # + reportId - The ID of the report to be downloaded. You can get the report ID in the (Get report list)[/other-api/revenue/operation/GET_ReportList] response
    # + headers - Headers to be sent with the request 
    # + return - The URL to download the report file. The signed URL will be valid for 30 minutes from the time when it is generated 
    remote isolated function getReportSignedUrl(int reportId, GetReportSignedUrlHeaders headers) returns ReportSignedUrlResponse|error {
        string resourcePath = string `/v2/reports/signedurl/${getEncodedUri(reportId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get staging error
    #
    # + errortype - The type of errors that you want to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Staging errors of the specified type are returned 
    remote isolated function getStagingErrors("transaction"|"event" errortype, GetStagingErrorsHeaders headers) returns StagingErrorResponse|error? {
        string resourcePath = string `/v1/stage/error/${getEncodedUri(errortype)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get field mapping
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Field mapping data is returned 
    remote isolated function getFieldMapping(GetFieldMappingHeaders headers, *GetFieldMappingQueries queries) returns FieldMappingResponse|error {
        string resourcePath = string `/v1/upload/mapping`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get all BI view task status
    #
    # + headers - Headers to be sent with the request 
    # + return - The task details are returned 
    remote isolated function listBiViewTasks(ListBiViewTasksHeaders headers) returns BiViewTaskListResponse|error? {
        string resourcePath = string `/v2/biviews-status`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get active task details
    #
    # + taskId - The continuation token that was returned in the initial request
    # + headers - Headers to be sent with the request 
    # + return - The details of active tasks that are associated with the continuation token are returned 
    remote isolated function getBiViewTask(string taskId, GetBiViewTaskHeaders headers) returns BiViewTaskDetailsResponse|error? {
        string resourcePath = string `/v2/biviews-status/${getEncodedUri(taskId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Cancel BI view download tasks
    #
    # + taskId - The continuation token that is associated with the tasks to be canceled
    # + headers - Headers to be sent with the request 
    # + return - The tasks associated with the specified continuation token are canceled 
    remote isolated function cancelBiViewTask(string taskId, CancelBiViewTaskHeaders headers) returns error? {
        string resourcePath = string `/v2/biviews-status/${getEncodedUri(taskId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Get BI view row count
    #
    # + tmplName - Name of the BI view
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The row count of the specified BI view is returned 
    remote isolated function getBiViewRowCount(string tmplName, GetBiViewRowCountHeaders headers, *GetBiViewRowCountQueries queries) returns error? {
        string resourcePath = string `/v2/biviews/count/${getEncodedUri(tmplName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Download BI view
    #
    # + viewName - Name of the BI view
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The queried BI view data is returned as a CSV or gzip file 
    remote isolated function downloadBiView(string viewName, DownloadBiViewHeaders headers, *DownloadBiViewQueries queries) returns byte[]|error? {
        string resourcePath = string `/v2/biviews/${getEncodedUri(viewName)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get column list
    #
    # + tmplName - Name of the BI view
    # + headers - Headers to be sent with the request 
    # + return - The list of columns is returned for the requested BI view 
    remote isolated function listBiViewColumns(string tmplName, ListBiViewColumnsHeaders headers) returns error? {
        string resourcePath = string `/v2/biviews/${getEncodedUri(tmplName)}/describe-columns`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Submit data collection job
    #
    # + headers - Headers to be sent with the request 
    # + payload - Data collection job request based on a revenue collection template 
    # + return - The request is submitted successfully and the job ID is returned. You can use the returned ID to query the job status later 
    remote isolated function createCollectionJob(RevenueJobRequest payload, map<string|string[]> headers = {}) returns RevenueJobResponse|error {
        string resourcePath = string `/v1/job/collection/template`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get data collection job details
    #
    # + jobId - The ID of the data collection job that you want to query. This is the ID that is returned when you submitted the data collection job
    # + headers - Headers to be sent with the request 
    # + return - The status of the data collection job is returned 
    remote isolated function getCollectionJob(int jobId, map<string|string[]> headers = {}) returns RevenueJobDetail|error {
        string resourcePath = string `/v1/job/collection/template/${getEncodedUri(jobId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get list of available programs and program parameters
    #
    # + headers - Headers to be sent with the request 
    # + return - A list of available programs is returned 
    remote isolated function listPrograms(map<string|string[]> headers = {}) returns ProgramDetailsResponse|error {
        string resourcePath = string `/v1/programs`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get list of available organizations
    #
    # + headers - Headers to be sent with the request 
    # + return - A list of available organizations is returned 
    remote isolated function listRevenueOrgs(map<string|string[]> headers = {}) returns ProgramDetailsResponse|error {
        string resourcePath = string `/v1/revenue-orgs`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Submit a program with specified parameters
    #
    # + programId - The ID of the program that is to be submitted in Zuora Revenue. You can get the program ID by using the "Get list of available programs and program parameters" operation
    # + orgId - The ID of the organization for which the program is to be submitted. You can get the organization ID by using the "Get list of available organizations" operation
    # + headers - Headers to be sent with the request 
    # + payload - An array that contains the parameter values to be used for the program. For each parameter, you need to specify the parameter ID, sequence, and desired value 
    # + return - The job status is returned with the job ID 
    remote isolated function submitProgram(int programId, int orgId, SubmitJobRequest payload, map<string|string[]> headers = {}) returns JobStatusResponse|error {
        string resourcePath = string `/v1/${getEncodedUri(orgId)}/programs/${getEncodedUri(programId)}/submit`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the job status
    #
    # + jobId - The ID of the Zuora Revenue job whose status is queried. This is the job ID returned when the program was submitted
    # + orgId - The ID of the organization that is specified when the job is submitted
    # + headers - Headers to be sent with the request 
    # + return - The job status is returned 
    remote isolated function getJobStatus(int jobId, int orgId, map<string|string[]> headers = {}) returns JobStatusResponse|error {
        string resourcePath = string `/v1/${getEncodedUri(orgId)}/jobs/${getEncodedUri(jobId)}`;
        return self.clientEp->get(resourcePath, headers);
    }
}
