// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

public type ProgramDetailsResponse record {
    ProgramDetail[] data?;
};

public type ReportListResponse record {
    # Response Message
    string Message?;
    ReportList[] Result?;
    # Response Status
    string status = "Success";
};

public type ProgramParameter record {
    string sequence?;
    string name?;
    int id?;
    string 'type?;
    string mandatory?;
};

public type TransferBatchStatusResponse record {
    # Response Status
    string status = "Success";
};

public type SubmitJobRequest record {
    ParameterList[] parameters?;
};

# Represents the Queries record for the operation: getUploadStatus
public type GetUploadStatusQueries record {
    # The request ID of the uploaded file for which the status information is being queried
    int id;
};

public type Journal record {
    @jsondata:Name {value: "crtd_dt"}
    string crtdDt?;
    @jsondata:Name {value: "updt_by"}
    string updtBy?;
    @jsondata:Name {value: "crtd_by"}
    string crtdBy?;
    @jsondata:Name {value: "report_id"}
    int:Signed32 reportId?;
    string name?;
    int:Signed32 id?;
    @jsondata:Name {value: "updt_dt"}
    string updtDt?;
    @jsondata:Name {value: "client_id"}
    int clientId?;
    string status?;
};

# Represents the Headers record for the operation: getFieldMapping
public type GetFieldMappingHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type RevenueJobResponse record {
    string message?;
    boolean success?;
};

# Represents the Queries record for the operation: getBiViewsForFields
public type GetBiViewsForFieldsQueries record {
    # The date from which the data query begins
    string fromDate = "2016-07-26T00:00:00";
    # The ID of the Zuora Revenue application user
    int clientId = 1;
    # The date on which the data query ends
    string toDate = "2016-07-26T00:00:00";
    # Set to `true` to get the row count of the BI view for the specified time period.
    # **Note:** Setting this parameter to `true` might cause timeout errors for large volume scenarios
    boolean count?;
    # The number of page to download
    int pagenum = 1;
};

public type BiViewTaskListResponse record {
    BiViewTaskListResult result?;
    # Response Status
    string status = "Success";
};

public type UploadFileResponse record {
    # Response Message
    string message = "File received successfully";
    # Response Status
    string status = "Success";
};

public type ActiveTasks record {
    @jsondata:Name {value: "activity_tracker"}
    ActiveActivityTracker activityTracker?;
    string metric?;
    int accumulate?;
    @jsondata:Name {value: "query_config"}
    ActiveQueryConfig queryConfig?;
    @jsondata:Name {value: "task_id"}
    string taskId?;
    string message?;
    string status?;
};

# Represents the Queries record for the operation: downloadBiView
public type DownloadBiViewQueries record {
    # The date from which the data query begins
    string fromDate = "2016-07-26T00:00:00";
    # The ID of the Zuora Revenue application user
    int clientId = 1;
    # The date on which the data query ends
    string toDate = "2018-07-26T00:00:00";
    # The number of rows on each page to be downloaded.
    # 
    # 
    # * For CSV format, the valid range is 1 - 10,000 with default 1,000.
    # * For gzip format, the valid range is 1 - 20,000 with default 1,000.
    # 
    # 
    # **Note:** Any value that is greater than 20,000 is invalid
    int pageSize?;
    # The output format of the download
    "csv"|"gzip" outputType = "gzip";
    # The number of page to be downloaded
    int pagenum = 1;
};

# Represents the Headers record for the operation: updateTransferBatchStatus
public type UpdateTransferBatchStatusHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

# Represents the Queries record for the operation: getBiViewRowCount
public type GetBiViewRowCountQueries record {
    # The date from which the data query begins
    string fromDate = "2016-07-26T00:00:00";
    # The ID of the Zuora Revenue application user
    int clientId = 1;
    # The date on which the data query ends
    string toDate = "2018-07-26T00:00:00";
};

public type CreateUploadResponse record {
    # Response Message
    string message = "Data Staged Successfully";
    CreateUploadResult result?;
    # Response Status
    string status = "Success";
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Headers record for the operation: downloadReport
public type DownloadReportHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type BiViewTaskDetailsResponse record {
    ActiveTasks[] active?;
    CompletedTasks[] completed?;
    DrainingTasks[] draining?;
    StaleTasks[] stale?;
};

public type JobStatusResponse record {
    JobStatus data?;
    boolean success?;
};

public type BiViewTaskListResult record {
    ActivityQueueStatus[] stale?;
    ActivityQueueStatus[] draining?;
    ActivityQueueStatus[] active?;
    ActivityQueueStatus[] completed?;
};

# Represents the Headers record for the operation: getStagingErrors
public type GetStagingErrorsHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

# Represents the Queries record for the operation: listReports
public type ListReportsQueries record {
    # The date when reports are created
    string createddate?;
};

public type FieldMappingResponse record {
    # Response Status
    string Dateformat = "DD-MON-YYYY";
    UploadMapping[] Mapping?;
};

# Represents the Headers record for the operation: listReports
public type ListReportsHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type ActivityQueueStatusQueryConfig record {
    @jsondata:Name {value: "filter_param"}
    ActivityQueueStatusQueryConfigFilterParam filterParam?;
    @jsondata:Name {value: "object_name"}
    string objectName?;
};

public type ProgramDetail record {
    @jsondata:Name {value: "program_name"}
    string programName?;
    @jsondata:Name {value: "program_id"}
    string programId?;
    ProgramParameter[] parameters?;
};

public type RevenueJobDetail record {
    RevenueJobDetailData data?;
    boolean success?;
};

# Represents the Headers record for the operation: createAuthentication
public type CreateAuthenticationHeaders record {
    # The Zuora Revenue user role that the token is generated for, for example the API role
    string role = "API Role";
    # The name of the client (application) that connects to Zuora Revenue
    string clientname = "Default";
};

public type ActiveQueryConfig record {
    @jsondata:Name {value: "object_name"}
    string objectName?;
    @jsondata:Name {value: "filter_params"}
    ActiveQueryConfigFilterParams filterParams?;
};

# Represents the Headers record for the operation: listBiViewColumns
public type ListBiViewColumnsHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type ParameterList record {
    int sequence = 1;
    @jsondata:Name {value: "parameter_value"}
    string parameterValue?;
    @jsondata:Name {value: "parameter_id"}
    int parameterId = 1002;
};

public type ActiveActivityTracker record {
    @jsondata:Name {value: "initated_time"}
    string initatedTime?;
    @jsondata:Name {value: "last_activity"}
    string lastActivity?;
    @jsondata:Name {value: "elapsed_time"}
    string elapsedTime?;
};

# Represents the Headers record for the operation: cancelBiViewTask
public type CancelBiViewTaskHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type StagingErrorResponse record {
    StageError[] Result?;
    # Response Status
    string status = "Success";
};

# Represents the Headers record for the operation: listTransferBatches
public type ListTransferBatchesHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

# Represents the Headers record for the operation: getTransferBatchFile
public type GetTransferBatchFileHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

# Represents the Queries record for the operation: getFieldMapping
public type GetFieldMappingQueries record {
    # Name of the upload template that contains the field mapping information
    string templatename?;
};

public type TransferBatchListResponse record {
    Journal[] result?;
    # Response Status
    string status = "Success";
};

# Represents the Headers record for the operation: getBiViewsForFields
public type GetBiViewsForFieldsHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type UploadStatusResult record {
    int id?;
    string message = "Data Received";
    @jsondata:Name {value: "client_id"}
    int clientId?;
    string status = "Successfully Uploaded";
};

# Represents the Headers record for the operation: downloadBiView
public type DownloadBiViewHeaders record {
    # The continuation token that was returned in the initial query for Page 1.
    # 
    # 
    # **Note:** The continuation token is returned after Page 1 of the BI view is downloaded.
    # To download the subsequent pages, you must specify the continuation token in this operation
    # for Page 2 onwards
    @http:Header {name: "continuation-token"}
    string continuationToken?;
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type JobStatus record {
    @jsondata:Name {value: "error_message"}
    string errorMessage?;
    @jsondata:Name {value: "crtd_dt"}
    string crtdDt?;
    @jsondata:Name {value: "actual_start_date"}
    string actualStartDate?;
    @jsondata:Name {value: "crtd_by"}
    string crtdBy?;
    int id?;
    @jsondata:Name {value: "updt_dt"}
    string updtDt?;
    @jsondata:Name {value: "sec_atr_val"}
    int secAtrVal?;
    string status?;
};

# Represents the Headers record for the operation: getUploadStatus
public type GetUploadStatusHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type DrainingTasks string;

public type UploadStatus record {
    @jsondata:Name {value: "file_request_id"}
    int fileRequestId?;
    @jsondata:Name {value: "file_log"}
    string fileLog?;
};

public type UploadStatusResponse record {
    UploadStatusResult result?;
    # Response Response
    string status = "Success";
};

# Represents the Headers record for the operation: createUpload
public type CreateUploadHeaders record {
    # The unique file name to populate the data in the Zuora Revenue UI
    string filename;
    # The name of the upload template that you want to use
    string templatename;
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type RevenueJobRequest record {
    # Name of the RC template that is defined in Zuora Revenue (**Policies > RC Grouping Template**).
    string rc_template_name?;
    # The organization ID that can be found in Zuora Revenue (**Setups > Application > Organization**). This field is required only for multi-organization tenants.
    int org_id = 0;
};

public type RevenueJobDetailData record {
    @jsondata:Name {value: "crtd_dt"}
    string crtdDt?;
    @jsondata:Name {value: "actual_start_date"}
    string actualStartDate?;
    @jsondata:Name {value: "crtd_by"}
    string crtdBy?;
    int id?;
    @jsondata:Name {value: "updt_dt"}
    string updtDt?;
    "Running"|"Error"|"Pending"|"Completed"|"Warning"|"Failed"|"Cancelled"|"Terminated"|"Incompatible" status?;
};

# Represents the Headers record for the operation: getBiViewTask
public type GetBiViewTaskHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

# Represents the Headers record for the operation: getBiViewRowCount
public type GetBiViewRowCountHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

# Represents the Headers record for the operation: getFileUploadStatus
public type GetFileUploadStatusHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type ActivityQueueStatusQueryConfigFilterParam record {
    string fromDate?;
    string toDate?;
};

public type UploadFileBody record {
    # The path to the CSV file that is to be uploaded
    record {byte[] fileContent; string fileName;} file;
};

public type CreateUploadResult record {
    int id?;
    string message?;
    @jsondata:Name {value: "client_id"}
    int clientId?;
    string status?;
};

# Represents the Queries record for the operation: getTransferBatch
public type GetTransferBatchQueries record {
    # The number of records to be downloaded per request. The default is 1000 and the maximum is 10000
    int pagesize?;
};

public type FileUploadStatusResponse record {
    UploadStatus[] Result?;
    # Response Message
    string message = "Data Staged Successfully";
    # Response Status
    string status = "Success";
};

# Represents the Queries record for the operation: getBiViews
public type GetBiViewsQueries record {
    # The date from which the data query begins
    string fromDate = "2016-07-26T00:00:00";
    # The ID of the Zuora Revenue application user
    int clientId = 1;
    # The date on which the data query ends
    string toDate = "2016-07-26T00:00:00";
    # The number of records to be downloaded per request. The default is 1000 and the maximum is 10000
    int pagesize?;
    # Set to `true` to get the row count of the BI view for the specified time period.
    # 
    # **Note:** Setting this parameter to `true` might cause timeout errors for large volume scenarios
    boolean count?;
    # The number of page to download
    int pagenum = 1;
};

# Represents the Headers record for the operation: getTransferBatch
public type GetTransferBatchHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type ActiveQueryConfigFilterParams record {
    string fromDate?;
    string toDate?;
};

public type StageError record {
    @jsondata:Name {value: "processed_flag"}
    string processedFlag?;
    @jsondata:Name {value: "upload_id"}
    string uploadId?;
    @jsondata:Name {value: "updt_by"}
    string updtBy?;
    @jsondata:Name {value: "so_num"}
    string soNum?;
    @jsondata:Name {value: "so_line_id"}
    string soLineId?;
    @jsondata:Name {value: "so_line_num"}
    string soLineNum?;
    @jsondata:Name {value: "updt_dt"}
    string updtDt?;
    string 'type?;
    @jsondata:Name {value: "sec_atr_val"}
    string secAtrVal?;
    @jsondata:Name {value: "client_id"}
    int clientId?;
    @jsondata:Name {value: "crtd_dt"}
    string crtdDt?;
    @jsondata:Name {value: "crtd_by"}
    string crtdBy?;
    @jsondata:Name {value: "err_msg"}
    string errMsg?;
    @jsondata:Name {value: "inv_line_num"}
    string invLineNum?;
    @jsondata:Name {value: "inv_line_id"}
    string invLineId?;
    int id?;
};

public type AuthenticationResponse record {
    # Token
    string Message = "Token Generated";
    # Response Status
    string status = "success";
};

public type ActivityQueueStatusActivityTracker record {
    @jsondata:Name {value: "initated_time"}
    string initatedTime?;
    @jsondata:Name {value: "last_activity"}
    string lastActivity?;
    @jsondata:Name {value: "elapsed_time"}
    string elapsedTime?;
};

# Represents the Headers record for the operation: uploadFile
public type UploadFileHeaders record {
    # Name of the upload template that you want to use
    string templatename;
    # The valid authentication token that is generated by the Authentication operation
    string token;
    # Must be set to "multipart/form-data"
    @http:Header {name: "Content-Type"}
    "multipart/form-data" contentType;
};

public type UploadMapping record {
    @jsondata:Name {value: "upload_id"}
    int uploadId?;
    @jsondata:Name {value: "data_type"}
    string dataType?;
    @jsondata:Name {value: "col_name"}
    string colName?;
    int id?;
    string label?;
    @jsondata:Name {value: "client_id"}
    int clientId?;
    int seq?;
};

# Represents the Headers record for the operation: getBiViews
public type GetBiViewsHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type TransferBatchFileResponse record {
    # Response Status
    anydata[] active?;
};

# Represents the Headers record for the operation: listBiViewTasks
public type ListBiViewTasksHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type CompletedTasks string;

# Represents the Headers record for the operation: getReportSignedUrl
public type GetReportSignedUrlHeaders record {
    # The valid authentication token that is generated by the Authentication operation
    string token;
};

public type ReportSignedUrlResponse record {
    # A valid signed URL to download the report.
    anydata signed_url?;
    # Indicates whether the operation succeeded.
    boolean success?;
};

public type ActivityQueueStatus record {
    @jsondata:Name {value: "activity_tracker"}
    ActivityQueueStatusActivityTracker activityTracker?;
    int metric?;
    int accumulate?;
    @jsondata:Name {value: "query_config"}
    ActivityQueueStatusQueryConfig queryConfig?;
    @jsondata:Name {value: "task_id"}
    string taskId?;
    string message?;
    string status?;
};

public type ReportList record {
    @jsondata:Name {value: "rep_desc"}
    string repDesc?;
    @jsondata:Name {value: "layout_name"}
    string layoutName?;
    @jsondata:Name {value: "rep_name"}
    string repName?;
    @jsondata:Name {value: "file_name"}
    string fileName?;
    int id?;
    string category?;
    @jsondata:Name {value: "report_date"}
    string reportDate?;
    string status?;
};

public type StaleTasks string;
